######################################################################
#  Create by XUEYL 2014-07-10. xueyunlong@gmail.com
######################################################################
TMPDIR = $(HOME)/tmp/
OSTYPE = -DOS_LINUX

#static dynamic
LINKSD = -static-libstdc++ -static-libgcc -static
#LINKSD = 

#PERFORMANCE = -DDEBUG -g
PERFORMANCE = -O3

ifeq ($(PERFORMANCE), -DDEBUG -g)
	FLAGS = -c $(OSTYPE) $(PERFORMANCE) -Wall -fsanitize=address -pg $(INCL)
	LDFLAGS = -lasan -pg $(LINKSD)
	STRIP = echo
else
	FLAGS = -c $(OSTYPE) $(PERFORMANCE) $(INCL)
	LDFLAGS = $(LINKSD)
	STRIP = strip
endif

AR = ar
ARFLAGS = -rcs

CC = gcc 
CLINK = gcc
#CSTD = -std=c99
CFLAGS = $(FLAGS) $(CSTD)  
CLDFLAGS = $(LDFLAGS)

CPP = g++
CPPLINK	= g++
CPPSTD = -std=c++11
CPPFLAGS = $(FLAGS) $(CPPSTD)
CPPLDFLAGS = $(LDFLAGS)

PROC= proc
PROCFLAGS = lines=yes parse=none mode=oracle close_on_commit=no dynamic=ansi

PROCPPFLAGS = lines=yes parse=none mode=oracle close_on_commit=no dynamic=ansi cpp_suffix=cpp
#LDFLAGS = -shared $(MACHINE) -lm -Wl,-Bsymbolic,--allow-shlib-undefined --no-whole-archive

#
# $@: holds the name of target
# $<: holds the source file name
# $*: holds the name equal to "%"
# 

%.o : %.c %.h
	$(CC) $(CFLAGS) $< -o $@
%.o : %.cpp %.h
	$(CPP) $(CPPFLAGS) $< -o $@
%.o : %.cc	%.h
	$(CPP) $(CPPFLAGS) $< -o $@
%.o : %.pc
	$(PROC) $(PROCFLAGS) iname=$< oname=$*.c
	$(CC) $(CFLAGS) $*.c -o $@
%.o : %.l
	flex -o $<.c  $< 
	$(CC) $(CFLAGS)	$<.c -o $@
