######################################################################
#  Create by XUEYL 2014-07-10. xueyunlong@gmail.com
######################################################################
TMPDIR = $(HOME)/tmp/


#PERFORMANCE = -O3
PERFORMANCE = -DDEBUG -g -Wall
#PERFORMANCE = -DDEBUG -g
OSTYPE = -DOS_LINUX
FLAGS = $(PERFORMANCE) $(OSTYPE) 

AR = ar
ARFLAGS = -rcs
SOFLAGS = -shared -fpic

CC = cc 
CLINK = cc
#CSTD = -std=c99
CFLAGS = -c $(FLAGS) $(CSTD) $(INCL)
CLDFLAGS = $(LIB_DIR) $(LIBS) 

CPP = g++
CPPLINK	= g++
CPPFLAGS = -c -std=c++11 $(FLAGS) $(INCL)
CPPLDFLAGS = 

PROC= proc
PROCFLAGS = lines=yes parse=none mode=oracle close_on_commit=no dynamic=ansi

PROCPPFLAGS = lines=yes parse=none mode=oracle close_on_commit=no dynamic=ansi cpp_suffix=cpp
#LDFLAGS = -shared $(MACHINE) -lm -Wl,-Bsymbolic,--allow-shlib-undefined --no-whole-archive

#
# $@: holds the name of target
# $<: holds the source file name
# $*: holds the name equal to "%"
# 

%.o : %.c
	-$(XTRACE) -c $<
	$(XTRACE) -o $<
	$(CC) $(CFLAGS) $< -o $@
%.so : %.c
	-$(XTRACE) -c $<
	$(XTRACE) -o $<
	$(CC) $(CFLAGS) $(SOFLAGS) $< -o $@
%.o : %.cpp
	-$(XTRACE) -c $<
	$(XTRACE) -o $<
	$(CPP) $(CPPFLAGS) $< -o $@
%.so : %.cpp
	-$(XTRACE) -c $<
	$(XTRACE) -o $<
	$(CPP) $(CPPFLAGS) $(SOFLAGS) $< -o $@
%.o : %.cc	%.h
	$(CPP) $(CPPFLAGS) $< -o $@
%.o : %.pc
	$(PROC) $(PROCFLAGS) iname=$< oname=$*.c
	$(CC) $(CFLAGS) $*.c -o $@
%.o : %.l
	flex -o $<.c  $< 
	$(CC) $(CFLAGS)	$<.c -o $@
